const js = require('@eslint/js');
const globals = require('globals');
const babelParser = require('@babel/eslint-parser');
const react = require('eslint-plugin-react');
const reactHooks = require('eslint-plugin-react-hooks');
const jsxA11y = require('eslint-plugin-jsx-a11y');
const prettier = require('eslint-config-prettier');

module.exports = [
  { ignores: ['.cache/', 'public/', 'node_modules/'] },
  js.configs.recommended,
  react.configs.flat.recommended,
  jsxA11y.flatConfigs.recommended,
  {
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        // babel-preset-gatsby needs config generated by the Gatsby CLI, so lint with plain JSX support
        babelOptions: { babelrc: false, configFile: false, presets: ['@babel/preset-react'] },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        graphql: 'readonly',
        __PATH_PREFIX__: 'readonly',
      },
    },
    plugins: { 'react-hooks': reactHooks },
    settings: { react: { version: 'detect' } },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/exhaustive-deps': 'off',
    },
  },
  prettier,
];
